# Generated by Django 5.2.12 on 2026-04-18 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='from_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_orders', to='locations.district'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_orders', to='locations.region'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to='locations.district'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to='locations.region'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.packagetype'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='orders_orde_trackin_04edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status__eb4f00_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_orde_user_id_a87c6f_idx'),
        ),
    ]
