# Generated by Django 5.2.12 on 2026-04-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_delete_district_alter_city_unique_together'),
        ('orders', '0003_remove_orderhistory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.region'),
        ),
    ]
