# Generated by Django 5.2.12 on 2026-04-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Viloyat nomi')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (Ruschada)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'db_table': 'locations_region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tuman nomi')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (Ruschada)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'db_table': 'locations_district',
                'ordering': ['region', 'name'],
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Filial nomi')),
                ('branch_type', models.CharField(choices=[('main', 'Markaziy filial'), ('regional', 'Viloyat filiali'), ('district', 'Tuman filiali'), ('pickup', 'Yetkazib olish punkti'), ('dropoff', 'Topshirish punkti')], default='district', max_length=20, verbose_name='Filial turi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Uzunlik')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('working_hours', models.CharField(default='09:00 - 18:00', max_length=100, verbose_name='Ish vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='locations.district', verbose_name='Tuman')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='locations.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'locations_branch',
                'ordering': ['region', 'district', 'name'],
            },
        ),
    ]
