# Generated by Django 5.2.12 on 2026-04-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='district',
            name='region',
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name_en'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='region',
            name='delivery_days_max',
            field=models.PositiveIntegerField(default=3, verbose_name='Max delivery days'),
        ),
        migrations.AddField(
            model_name='region',
            name='delivery_days_min',
            field=models.PositiveIntegerField(default=1, verbose_name='Min delivery days'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (Ruschada)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('is_hub', models.BooleanField(default=False, verbose_name='Is hub')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'locations_city',
                'ordering': ['region', 'name_en'],
            },
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
