# Generated by Django 5.2.12 on 2026-04-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_district_unique_together_and_more'),
        ('orders', '0003_remove_orderhistory_created_by_and_more'),
        ('users', '0002_remove_useraddress_district_user_is_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name_en')},
        ),
    ]
