# Generated by Django 5.2.13 on 2026-04-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_useraddress_district_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
    ]
