# Generated by Django 5.2.12 on 2026-04-27 09:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_simplify_useraddress'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='full_address',
            field=models.TextField(),
        ),
    ]
