"""
Seed data for Uzbekistan regions and cities
"""

REGIONS_DATA = [
    {
        "name_uz": "Toshkent shaxri",
        "name_ru": "Город Ташкент",
        "name_en": "Tashkent",
        "code": "TK",
        "delivery_days_min": 1,
        "delivery_days_max": 1,
    },
    {
        "name_uz": "Andijan viloyati",
        "name_ru": "Андижанская область",
        "name_en": "Andijan Region",
        "code": "AN",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
    },
    {
        "name_uz": "Bukhara viloyati",
        "name_ru": "Бухарская область",
        "name_en": "Bukhara Region",
        "code": "BU",
        "delivery_days_min": 2,
        "delivery_days_max": 4,
    },
    {
        "name_uz": "Fergona viloyati",
        "name_ru": "Ферганская область",
        "name_en": "Fergona Region",
        "code": "FG",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
    },
    {
        "name_uz": "Jizzax viloyati",
        "name_ru": "Джизакская область",
        "name_en": "Jizzakh Region",
        "code": "JZ",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
    },
    {
        "name_uz": "Xorazm viloyati",
        "name_ru": "Хорезмская область",
        "name_en": "Khorezm Region",
        "code": "KH",
        "delivery_days_min": 2,
        "delivery_days_max": 4,
    },
    {
        "name_uz": "Namangan viloyati",
        "name_ru": "Наманганская область",
        "name_en": "Namangan Region",
        "code": "NM",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
    },
    {
        "name_uz": "Navoi viloyati",
        "name_ru": "Навойская область",
        "name_en": "Navoi Region",
        "code": "NV",
        "delivery_days_min": 2,
        "delivery_days_max": 4,
    },
    {
        "name_uz": "Samarkand viloyati",
        "name_ru": "Самаркандская область",
        "name_en": "Samarkand Region",
        "code": "SM",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
    },
    {
        "name_uz": "Sirdarya viloyati",
        "name_ru": "Сырдарьинская область",
        "name_en": "Sirdarya Region",
        "code": "SR",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
    },
    {
        "name_uz": "Surxondarya viloyati",
        "name_ru": "Сурхандарьинская область",
        "name_en": "Surkhandarya Region",
        "code": "SU",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
    },
    {
        "name_uz": "Tashkent viloyati",
        "name_ru": "Ташкентская область",
        "name_en": "Tashkent Region",
        "code": "TA",
        "delivery_days_min": 1,
        "delivery_days_max": 2,
    },
    {
        "name_uz": "Qashqadarya viloyati",
        "name_ru": "Кашкадарьинская область",
        "name_en": "Kashkadarya Region",
        "code": "QA",
        "delivery_days_min": 2,
        "delivery_days_max": 3,
    },
]

CITIES_DATA = [
    # Tashkent City
    {
        "region_code": "TK",
        "name_uz": "Toshkent",
        "name_ru": "Ташкент",
        "name_en": "Tashkent",
        "is_hub": True,
    },
    # Tashkent Region
    {
        "region_code": "TA",
        "name_uz": "Tashkent",
        "name_ru": "Ташкент",
        "name_en": "Tashkent",
        "is_hub": True,
    },
    {
        "region_code": "TA",
        "name_uz": "Chirchiq",
        "name_ru": "Чирчик",
        "name_en": "Chirchik",
        "is_hub": False,
    },
    {
        "region_code": "TA",
        "name_uz": "Yangiyul",
        "name_ru": "Янгиюль",
        "name_en": "Yangiyul",
        "is_hub": False,
    },
    # Andijan Region
    {
        "region_code": "AN",
        "name_uz": "Andijan",
        "name_ru": "Андижан",
        "name_en": "Andijan",
        "is_hub": True,
    },
    {
        "region_code": "AN",
        "name_uz": "Asaka",
        "name_ru": "Асака",
        "name_en": "Asaka",
        "is_hub": False,
    },
    {
        "region_code": "AN",
        "name_uz": "Qo'qon",
        "name_ru": "Коканд",
        "name_en": "Kokand",
        "is_hub": False,
    },
    {
        "region_code": "AN",
        "name_uz": "Margilon",
        "name_ru": "Маргилан",
        "name_en": "Margilan",
        "is_hub": False,
    },
    # Bukhara Region
    {
        "region_code": "BU",
        "name_uz": "Buxoro",
        "name_ru": "Бухара",
        "name_en": "Bukhara",
        "is_hub": True,
    },
    {
        "region_code": "BU",
        "name_uz": "Gijduvon",
        "name_ru": "Гиждуван",
        "name_en": "Gijduvon",
        "is_hub": False,
    },
    {
        "region_code": "BU",
        "name_uz": "Navoi",
        "name_ru": "Навои",
        "name_en": "Navoi",
        "is_hub": False,
    },
    # Fergona Region
    {
        "region_code": "FG",
        "name_uz": "Fergona",
        "name_ru": "Фергона",
        "name_en": "Fergona",
        "is_hub": True,
    },
    {
        "region_code": "FG",
        "name_uz": "Qo'qon",
        "name_ru": "Коканд",
        "name_en": "Kokand",
        "is_hub": False,
    },
    {
        "region_code": "FG",
        "name_uz": "Margilon",
        "name_ru": "Маргилан",
        "name_en": "Margilan",
        "is_hub": False,
    },
    # Jizzakh Region
    {
        "region_code": "JZ",
        "name_uz": "Jizzax",
        "name_ru": "Джизак",
        "name_en": "Jizzakh",
        "is_hub": True,
    },
    {
        "region_code": "JZ",
        "name_uz": "Zarbdor",
        "name_ru": "Зарбдор",
        "name_en": "Zarbdor",
        "is_hub": False,
    },
    # Khorezm Region
    {
        "region_code": "KH",
        "name_uz": "Urganch",
        "name_ru": "Ургенч",
        "name_en": "Urgench",
        "is_hub": True,
    },
    {
        "region_code": "KH",
        "name_uz": "Xiva",
        "name_ru": "Хива",
        "name_en": "Khiva",
        "is_hub": False,
    },
    # Namangan Region
    {
        "region_code": "NM",
        "name_uz": "Namangan",
        "name_ru": "Наманган",
        "name_en": "Namangan",
        "is_hub": True,
    },
    {
        "region_code": "NM",
        "name_uz": "Pop",
        "name_ru": "Поп",
        "name_en": "Pop",
        "is_hub": False,
    },
    # Navoi Region
    {
        "region_code": "NV",
        "name_uz": "Navoi",
        "name_ru": "Навои",
        "name_en": "Navoi",
        "is_hub": True,
    },
    {
        "region_code": "NV",
        "name_uz": "Zarafshon",
        "name_ru": "Зарафшан",
        "name_en": "Zarafshan",
        "is_hub": False,
    },
    # Samarkand Region
    {
        "region_code": "SM",
        "name_uz": "Samarkand",
        "name_ru": "Самарканд",
        "name_en": "Samarkand",
        "is_hub": True,
    },
    {
        "region_code": "SM",
        "name_uz": "Payariq",
        "name_ru": "Пайарык",
        "name_en": "Payariq",
        "is_hub": False,
    },
    # Sirdarya Region
    {
        "region_code": "SR",
        "name_uz": "Sirdarya",
        "name_ru": "Сырдарья",
        "name_en": "Sirdarya",
        "is_hub": True,
    },
    {
        "region_code": "SR",
        "name_uz": "Xo'jayli",
        "name_ru": "Хожаили",
        "name_en": "Khojayli",
        "is_hub": False,
    },
    # Surkhandarya Region
    {
        "region_code": "SU",
        "name_uz": "Termiz",
        "name_ru": "Термез",
        "name_en": "Termiz",
        "is_hub": True,
    },
    {
        "region_code": "SU",
        "name_uz": "Denov",
        "name_ru": "Денов",
        "name_en": "Denov",
        "is_hub": False,
    },
    # Kashkadarya Region
    {
        "region_code": "QA",
        "name_uz": "Qashqadarya",
        "name_ru": "Кашкадарья",
        "name_en": "Kashkadarya",
        "is_hub": True,
    },
    {
        "region_code": "QA",
        "name_uz": "Qamash",
        "name_ru": "Камаш",
        "name_en": "Kamash",
        "is_hub": False,
    },
]
